// Outdoor Boys — data model (standalone build — uses window.__resources)
const R = window.__resources;

const IMG = {
  hero:        R.zhuiluView,
  heroAlt:     R.tarokoRiver,
  heroAlt2:    R.shakadangRiver,
  canyon:      R.tarokoRiver,
  pool:        R.shakadangRiver,
  waterfall:   R.canyoningLuoshan,
  forest:      R.canyonPool,
  stream:      R.canyonPool,
  gorge:       R.zhuiluView,
  misty:       R.zhuiluView,
  jungle:      R.canyonPool,
  rapids:      R.canyoningLuoshan,
  emerald:     R.shakadangRiver,
  team:        R.teamWaterfall,
  climber:     R.canyoningLuoshan,
  guide1:      R.teamWaterfall,
  guide2:      R.canyoningLuoshan,
  guide3:      R.tarokoRiver,
  gear:        R.canyonPool,
};

// Routes — Nan'ao, Yilan area (matches scope-roadmap: 鹿皮溪 + 金岳 pilots)
const TOURS = [
  {
    id: "luopi",
    name: "Luopi Stream",
    zh: "鹿皮溪",
    tier: "Beginner",
    tierZh: "入門",
    hours: 6,
    distance: 3.0,
    elev: 140,
    price: 3200,
    river: "Luopi",
    features: ["Swim-through pools", "Short jumps 3–5m", "Forest approach"],
    summary: "Our flagship pilot route. Gentle jade pools, a 4m jump for those who want it, and a long lunch in the sun.",
    photo: IMG.forest,
    coord: "24.4620° N, 121.7542° E",
  },
  {
    id: "jinyue",
    name: "Jinyue Canyon",
    zh: "金岳峽谷",
    tier: "Intermediate",
    tierZh: "進階",
    hours: 8,
    distance: 5.4,
    elev: 260,
    price: 4400,
    river: "Jinyue",
    features: ["Cliff jumps to 8m", "Rope-assisted traverses", "Waterfall pool"],
    summary: "A full day threading the Jinyue gorge. One rope-assisted traverse, two optional jumps, one very blue pool.",
    photo: IMG.canyon,
    coord: "24.4711° N, 121.7201° E",
  },
  {
    id: "nanao",
    name: "Nan'ao South Fork",
    zh: "南澳南溪",
    tier: "Intermediate",
    tierZh: "進階",
    hours: 9,
    distance: 6.2,
    elev: 320,
    price: 4800,
    river: "Nan'ao South",
    features: ["Waterfall climb", "Low crowds", "Atayal territory"],
    summary: "A seldom-traveled fork ending beneath a 22-meter veil. We brief on Atayal land and tread accordingly.",
    photo: IMG.waterfall,
    coord: "24.4208° N, 121.7540° E",
  },
  {
    id: "aohua",
    name: "Aohua Hot Pool",
    zh: "澳花溫泉溪",
    tier: "Beginner",
    tierZh: "入門",
    hours: 5,
    distance: 2.2,
    elev: 60,
    price: 2800,
    river: "Aohua",
    features: ["Natural hot spring finish", "Family-friendly", "Photo-forward"],
    summary: "A short descent finishing at a wild riverbed hot spring. The softest entry point we offer.",
    photo: IMG.emerald,
    coord: "24.3981° N, 121.7725° E",
  },
  {
    id: "hanxi",
    name: "Hanxi Narrows",
    zh: "寒溪峽",
    tier: "Advanced",
    tierZh: "高階",
    hours: 10,
    distance: 7.6,
    elev: 440,
    price: 6000,
    river: "Hanxi",
    features: ["Abseil 15m+", "Class III current", "Committing"],
    summary: "Our most technical descent. A real canyon day — multi-pitch abseils, a long swim, a steady head.",
    photo: IMG.rapids,
    coord: "24.5902° N, 121.6840° E",
  },
  {
    id: "wudi",
    name: "Wudi Upper",
    zh: "武荖坑溪源",
    tier: "Advanced",
    tierZh: "高階",
    hours: 11,
    distance: 8.8,
    elev: 560,
    price: 6400,
    river: "Wudi",
    features: ["Multi-pitch abseils", "Overnight option", "Remote"],
    summary: "Two days, one canyon — spring through autumn only. Our most committing descent. Limited to six per season.",
    photo: IMG.gorge,
    coord: "24.6118° N, 121.6202° E",
  },
];

// Founders — real team from README
const GUIDES = [
  {
    name: "Dino",
    surname: "Hsu",
    role: "Lead Guide · Strategy",
    zh: "許 · 主嚮",
    years: 0, // pre-launch
    photo: IMG.guide1,
    bio: "Climbing background. Comfortable on technical rope and rappel. Speaks English, 中文, and a conversational 日本語.",
    cert: "山域嚮導 — 溯溪類",
    lang: "EN · 中 · 日",
    initial: "DH",
  },
  {
    name: "Luke",
    surname: "In-country Ops",
    role: "Ops · Permits · Co-guide",
    zh: "副嚮 · 運營",
    years: 0,
    photo: IMG.guide2,
    bio: "Avid hiker. Established relationships across Yilan county offices and Nanao vendors. Handles permits and the 14-day filing SOP.",
    cert: "山域嚮導 — 健行類",
    lang: "中 · 台語",
    initial: "LU",
  },
  {
    name: "Duncan",
    surname: "Water Safety",
    role: "Safety Officer · Brand Voice",
    zh: "水上安全官",
    years: 0,
    photo: IMG.guide3,
    bio: "Strongest swimmer on the team. Water-safety officer on every trip. Runs the English brand voice; relocating to Taiwan in Year 2.",
    cert: "Rescue 3 SRT",
    lang: "EN · 中",
    initial: "DC",
  },
  {
    name: "Apple",
    surname: "Sales · Hospitality",
    role: "Sales · CS · JP channel",
    zh: "銷售 · 客服",
    years: 0,
    photo: IMG.team,
    bio: "Strongest social + sales skills in the group. Runs hospitality on-trip, customer ops, and the Japanese-market channel.",
    cert: "紅十字會 救生員 · CPR/BLS",
    lang: "中 · 日 · EN",
    initial: "AP",
  },
];

const DAY = [
  { t:"06:30", title:"Breakfast, brief, bind the packs",  titleZh:"早餐、簡報、整理裝備", detail:"Congee and fruit at the Nanao base. Route card, weather call, gear check." },
  { t:"08:00", title:"Approach through fern understory",  titleZh:"蕨叢切入溯登點",       detail:"A 40-minute walk-in under camphor and banyan. Cicadas if it's summer." },
  { t:"09:15", title:"Put-in — first pool",                titleZh:"下溪 — 第一個潭",       detail:"Cold shock (18°C), buoyancy check, a short swim between marble walls." },
  { t:"11:00", title:"The narrows",                         titleZh:"穿越峽口",               detail:"Sidewall scrambles, a rope-assisted traverse, and a 6m jump for those who want it." },
  { t:"13:00", title:"Lunch on the sun rock",               titleZh:"午餐,太陽岩",           detail:"Handmade onigiri, pickled mustard, black tea. The kingfishers watch." },
  { t:"14:30", title:"The glass room",                      titleZh:"玻璃潭",                 detail:"An hour in the pool beneath the veil. Bring goggles; the light angles through at two." },
  { t:"16:30", title:"Take-out, dry out, drive home",       titleZh:"收隊、換裝、返程",       detail:"Hot towels, a Taiwan Beer, and the long curve back to Nanao." },
];

const SAFETY = [
  { k:"Helmet + PFD", kZh:"頭盔 + 救生衣", v:"Every descent, every grade. No exceptions, not even for the 4m section." },
  { k:"Swift-water rescue", kZh:"急流救援", v:"Duncan holds Rescue 3 SRT. Dino holds 溯溪類. Every trip runs with a certified water-safety officer." },
  { k:"Small groups", kZh:"小團制", v:"Max 6 clients per 2 guides. We turn groups away before we compromise the ratio." },
  { k:"14-day filing", kZh:"14 天事前報備", v:"Every trip is filed with Yilan authorities at least 14 days in advance. No cowboy runs." },
  { k:"Weather window", kZh:"氣象窗口", v:"Free reschedule if the river runs high. Flash floods in Taiwan are not theoretical." },
  { k:"Insurance", kZh:"保險", v:"公共意外責任保險 with 溯溪 rider, included in every booking." },
];

const PRESS = [
  "Pre-launch · Soft open Q3 2026",
  "First inbound trips · April 2027",
  "Based in Nanao, Yilan",
  "English-first · 日本語 also available",
];

window.LIWU = { IMG, TOURS, GUIDES, DAY, SAFETY, PRESS };
